let empleados = [
  {
    id: 1,
    nombre: "Jonás",
    apellido: "Busto",
    foto_perfil:
      "https://media.tenor.com/HDlcmUVa3w8AAAAd/messi-lionel-messi.gif",
    direccion: "Rivadavia 100A",
    fecha_nac: "2000-01-01",
    sexo: "h",
    email: "jonas@gmail.com",
    telefono: "123456789",
    id_rol: 5,
    id_supervisor: 6,
  },
  {
    id: 2,
    nombre: "Nacho",
    apellido: "Rebolleda",
    foto_perfil:
      "https://media.tenor.com/HDlcmUVa3w8AAAAd/messi-lionel-messi.gif",
    direccion: "Rivadavia 100A",
    fecha_nac: "2000-01-01",
    sexo: "h",
    email: "nacho@gmail.com",
    telefono: "123456789",
    id_rol: 9,
    id_supervisor: 6,
  },
  {
    id: 3,
    nombre: "Javier",
    apellido: "Paez",
    foto_perfil:
      "https://media.tenor.com/HDlcmUVa3w8AAAAd/messi-lionel-messi.gif",
    direccion: "Rivadavia 100A",
    fecha_nac: "2000-01-01",
    sexo: "h",
    email: "paez@gmail.com",
    telefono: "123456789",
    id_rol: 8,
    id_supervisor: 6,
  },
  {
    id: 4,
    nombre: "Felix",
    apellido: "Figueroa",
    foto_perfil:
      "https://media.tenor.com/HDlcmUVa3w8AAAAd/messi-lionel-messi.gif",
    direccion: "Rivadavia 100A",
    fecha_nac: "2000-01-01",
    sexo: "h",
    email: "felix@gmail.com",
    telefono: "123456789",
    id_rol: 16,
    id_supervisor: 6,
  },
  {
    id: 5,
    nombre: "Leandro",
    apellido: "Bechara",
    foto_perfil:
      "https://media.tenor.com/HDlcmUVa3w8AAAAd/messi-lionel-messi.gif",
    direccion: "Rivadavia 100A",
    fecha_nac: "2000-01-01",
    sexo: "h",
    email: "leandro@gmail.com",
    telefono: "123456789",
    id_rol: 17,
    id_supervisor: 6,
  },
  {
    id: 6,
    nombre: "Lucas",
    apellido: "Cordero",
    foto_perfil:
      "https://media.tenor.com/HDlcmUVa3w8AAAAd/messi-lionel-messi.gif",
    direccion: "Rivadavia 100A",
    fecha_nac: "2000-01-01",
    sexo: "h",
    email: "profesor@gmail.com",
    telefono: "123456789",
    id_rol: 2,
    id_supervisor: 6,
  },
];

export default empleados;
